language: php

php:
  - 7.1

branches:
  only:
    - master
    - development
    - /^feature\/.+$/
    - /^refactoring\/.+$/
    - /^issue\/.+$/

before_script:
 - for file in `ls -1 ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/`; do echo "$file\n" && cat $file; done
