language: php

php:
  - 7.1

branches:
  only:
    - master
    - development
    - /^feature\/.+$/
    - /^refactoring\/.+$/
    - /^issue\/.+$/

before_script:
 - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
 - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
 - git checkout "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
 - git reset --hard "$TRAVIS_COMMIT"
 - composer self-update
 - mkdir -p vendor/bin
 - composer install -o --prefer-dist --no-interaction
 - mkdir build/logs

script:
 - php vendor/bin/phpunit.phar -c build/
